#!/bin/bash

# build site with jekyll, by default to `_site' folder
bundle exec jekyll build

# initialize new repo from newly built _site folder
echo "--- INITIALISING NEW REPO ---"
cd /home/travis/build/the-engine-room/library/_site
git init
git config user.email "mayarichman@gmail.com"
git config user.name "${GH_USERNAME}"
git remote add upstream https://${GH_USERNAME}:${GH_TOKEN}@github.com/${GH_OWNER}/${GH_REPO}.git
git fetch upstream
git reset upstream/gh-pages
touch .nojekyll

# add, commit and push changes to master
echo "--- ADDING ALL... ---"
git add -A .
echo "--- COMMITTING NOW... ---"
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
echo "--- PUSH EVERYTHING! ALL THE THINGS, PUSH THEM! ---"
git push --force --verbose "https://mayarichman:${GH_TOKEN}@github.com/the-engine-room/library.git" master:master > /dev/null 2>&1 
echo $?
