#!/bin/bash
 cd /home/travis/build/the-engine-room/library/_site/
 git init
 git config user.name "mayarichman"
 git config user.email "mayarichman@gmail.com"
 git remote add upstream https://${GH_TOKEN}@github.com/the-engine-room/library.git
 git fetch upstream
 git reset upstream/testing-travis
 touch .nojekyll
 git add --all
 git commit -m \"Travis build $TRAVIS_BUILD_NUMBER\"
 git push --quiet upstream HEAD:testing-travis
